### ISSUE TITLE
Create an `aging_report/core_integrator/` sub-package

### ISSUE THREAD

**Issue by widal001** [department-of-general-services/priority-vendor-aging-report#18]
## Summary 

Sub-task of #17 to set up the basic sub-package file structure

## Tasks

- [ ] Add the following modules to `aging_report/core_integrator/` 
  - [ ] `utils.py` Used to create common functions used by Selenium chrome driver
  - [ ] `scraper.py` With a `CoreIntegrator` class that actually downloads the report from CoreIntegrator
  - [ ] `prompt_payment.py` With a `PromptPayment` class that manages calls to other classes and functions
- [ ] Create the following test folders:
  - [ ] `tests/integration_tests/core_integrator/`
  - [ ] `tests/unit_tests/core_integrator/`
- [ ] Add the following packages to the project:
  - [ ] `selenium`
  - [ ] `pandas`
  - [ ] `xlwings`

## Definition of Done

- [ ] The scaffolding for the other issues in #17 has been built
